# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_TEST.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(10, 6, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.result.setFont(font)
        self.result.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"color: rgb(255, 0, 0);\n"
"font: 63 16pt \"Yu Gothic UI Semibold\";")
        self.result.setObjectName("result")
        self.sem = QtWidgets.QPushButton(self.centralwidget)
        self.sem.setGeometry(QtCore.QRect(10, 50, 93, 81))
        self.sem.setObjectName("sem")
        self.devyat = QtWidgets.QPushButton(self.centralwidget)
        self.devyat.setGeometry(QtCore.QRect(300, 50, 93, 81))
        self.devyat.setObjectName("devyat")
        self.odin = QtWidgets.QPushButton(self.centralwidget)
        self.odin.setGeometry(QtCore.QRect(10, 250, 93, 81))
        self.odin.setObjectName("odin")
        self.chetiri = QtWidgets.QPushButton(self.centralwidget)
        self.chetiri.setGeometry(QtCore.QRect(10, 150, 93, 81))
        self.chetiri.setObjectName("chetiri")
        self.vosem = QtWidgets.QPushButton(self.centralwidget)
        self.vosem.setGeometry(QtCore.QRect(150, 50, 93, 81))
        self.vosem.setObjectName("vosem")
        self.shest = QtWidgets.QPushButton(self.centralwidget)
        self.shest.setGeometry(QtCore.QRect(300, 150, 93, 81))
        self.shest.setObjectName("shest")
        self.tri = QtWidgets.QPushButton(self.centralwidget)
        self.tri.setGeometry(QtCore.QRect(300, 250, 93, 81))
        self.tri.setObjectName("tri")
        self.pyat = QtWidgets.QPushButton(self.centralwidget)
        self.pyat.setGeometry(QtCore.QRect(150, 150, 93, 81))
        self.pyat.setObjectName("pyat")
        self.dvA = QtWidgets.QPushButton(self.centralwidget)
        self.dvA.setGeometry(QtCore.QRect(150, 250, 93, 81))
        self.dvA.setObjectName("dvA")
        self.nol = QtWidgets.QPushButton(self.centralwidget)
        self.nol.setGeometry(QtCore.QRect(10, 360, 161, 81))
        self.nol.setObjectName("nol")
        self.ravno = QtWidgets.QPushButton(self.centralwidget)
        self.ravno.setGeometry(QtCore.QRect(222, 360, 171, 81))
        self.ravno.setObjectName("ravno")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.result.setText(_translate("MainWindow", "0"))
        self.sem.setText(_translate("MainWindow", "7"))
        self.devyat.setText(_translate("MainWindow", "9"))
        self.odin.setText(_translate("MainWindow", "1"))
        self.chetiri.setText(_translate("MainWindow", "4"))
        self.vosem.setText(_translate("MainWindow", "8"))
        self.shest.setText(_translate("MainWindow", "6"))
        self.tri.setText(_translate("MainWindow", "3"))
        self.pyat.setText(_translate("MainWindow", "5"))
        self.dvA.setText(_translate("MainWindow", "2"))
        self.nol.setText(_translate("MainWindow", "0"))
        self.ravno.setText(_translate("MainWindow", "="))

if __name__ == "__main_":
    setupUi()